### ISSUE TITLE
Starting the JBoss EAP standalone server fails due to permissions

### ISSUE THREAD

**Issue by jramcast** [RedHatQuickCourses/eap-admin1#18]
This particular step fails when the server tries to create the directory `/opt/jboss-eap-installation-manager-1.1.6.Final-redhat-00001/bin/eap-8/standalone/data`.

https://redhatquickcourses.github.io/eap-admin1/eap-admin1/8/install/install.html#_lab_1_installing_jboss_eap_using_the_eap_8_installation_manager

![image](https://github.com/RedHatQuickCourses/eap-admin1/assets/675470/2fbf8940-68c0-478b-a23e-25f7c572b765)

I solved the issue by changing the owner of the installation manager directory (previously it was owned by root):

```sh
cd /opt
sudo chown jboss:jboss -R jboss-eap-installation-manager-1.1.6.Final-redhat-00001/
```

**Comment by bcsepregi** [comment]
Hello,
I think you need to chown only the server instance folder. The below command worked for me:
chown jboss:jboss -R jboss-eap-installation-manager-1.1.6.Final-redhat-00001/bin/eap-8/

**Comment by YogiSoni-lazy** [comment]
Thanks for reporting this issue. Fixed the step. Closing the issue as of now.
